from copy import deepcopy

from literacy_cases_4 import CASE_LIBRARY as _BASE_CASE_LIBRARY

# 기존 3개씩의 검증 사례를 유지하면서, 주제별 6개를 추가해 총 9개 사례 풀을 구성합니다.
# 화면에 표시되는 source_excerpt는 각 연결 원문의 짧은 직접 발췌이며,
# 최종 판정은 사례별 resolution과 검증 단서를 통해 AI 대화에서 단계적으로 다룹니다.
CASE_LIBRARY = deepcopy(_BASE_CASE_LIBRARY)

CASE_LIBRARY["news"].extend([
    {
        "id": "news_kumamoto_old_footage",
        "label": "AFP 팩트체크 · 맥락 오류",
        "title": "2026 구마모토 지진으로 퍼진 2024년 영상",
        "claim": "2026년 7월 구마모토 지진 직후 SNS에서 당시 지진 장면이라고 소개된 영상이 확산됐습니다.",
        "source_name": "AFP Fact Check · Outdated footage circulates after Kumamoto earthquake in Japan",
        "source_url": "https://factcheck.afp.com/doc.afp.com.C3GZ863",
        "media_type": "article",
        "media_url": "",
        "media_caption": "AFP가 영상의 원 게시물과 장소를 추적한 실제 팩트체크 사례입니다.",
        "source_excerpt": "But one video widely claimed online to show the tremor is old and unrelated",
        "opening_question": "SNS에서 ‘2026년 구마모토 지진 현장’이라는 설명과 함께 영상이 빠르게 퍼졌어. 영상이 실제처럼 보여도 바로 이번 지진 영상이라고 믿어도 될까? 가장 먼저 확인할 것을 말해줘.",
        "resolution": "AFP는 역이미지 검색과 원 게시물 추적을 통해 해당 영상이 2026년 구마모토 지진이 아니라 2024년 노토반도 지진 때 촬영된 영상임을 확인했습니다.",
        "clues": ["영상이 처음 게시된 시점 확인", "키프레임으로 역이미지 검색", "원 게시자의 장소 설명 확인", "건물·신사 구조를 지도·사진과 대조"],
    },
    {
        "id": "news_ai_horse_quake",
        "label": "AFP 팩트체크 · AI 생성 영상",
        "title": "지진 때 주인을 감싼 말 영상",
        "claim": "2026년 일본 지진 뒤 말이 주인을 몸으로 보호하는 장면이라는 영상이 SNS에서 공유됐습니다.",
        "source_name": "AFP Fact Check · AI-generated clip of horse shielding owner during Japan quake",
        "source_url": "https://factcheck.afp.com/doc.afp.com.A92T9WE",
        "media_type": "article",
        "media_url": "",
        "media_caption": "AFP가 게시 시점과 영상의 시각적 오류를 확인한 실제 팩트체크입니다.",
        "source_excerpt": "footage of a horse supposedly protecting its owner during the disaster shared online is actually AI-generated",
        "opening_question": "지진 중 말이 주인을 감싸 보호하는 영상이 감동적인 실제 장면처럼 퍼졌어. 영상 자체가 자연스러워 보인다는 이유만으로 실제 촬영이라고 판단해도 될까? 무엇부터 확인할지 말해줘.",
        "resolution": "AFP는 영상이 지진 발생 전부터 온라인에 존재했고, 물통·벽 등 장면에 AI 생성 영상 특유의 시각적 불일치가 있음을 확인했습니다.",
        "clues": ["지진 발생 전 동일 영상이 있었는지 확인", "영상 속 물체와 움직임의 일관성 확인", "원 게시 계정의 다른 콘텐츠 확인", "탐지 도구 결과만으로 단정하지 않고 출처와 함께 검증"],
    },
    {
        "id": "news_ai_cctv_quake",
        "label": "AFP 팩트체크 · AI 생성 CCTV",
        "title": "일본 지진 CCTV로 퍼진 AI 생성 영상",
        "claim": "2026년 일본 지진 당시 고층 건물이 크게 흔들리는 CCTV 영상이라는 게시물이 여러 언어로 확산됐습니다.",
        "source_name": "AFP Fact Check · Supposed CCTV clip showing northern Japan earthquake is AI-generated",
        "source_url": "https://factcheck.afp.com/doc.afp.com.A8TT3KQ",
        "media_type": "article",
        "media_url": "",
        "media_caption": "AFP가 과거 게시물과 영상 내부의 시각적 불일치를 비교한 사례입니다.",
        "source_excerpt": "The clip circulated months before the quake and contains visual errors commonly found in AI-generated content.",
        "opening_question": "CCTV 화면처럼 보이는 영상에서 건물들이 심하게 흔들리고 있어. ‘CCTV니까 조작이 아닐 것’이라고 생각해도 될까? 어떤 단서를 먼저 확인하겠어?",
        "resolution": "AFP는 같은 영상이 지진 이전인 2025년 12월부터 게시됐고, 표지판 글자와 횡단보도 등 장면에 AI 생성 흔적이 있음을 확인했습니다.",
        "clues": ["영상 타임스탬프와 최초 게시 시점 확인", "간판·도로 표시 등 세부 이미지의 일관성 확인", "카메라 흔들림과 주변 물체 움직임 비교", "게시 계정의 과거 AI 콘텐츠 여부 확인"],
    },
    {
        "id": "news_philippines_recycled_video",
        "label": "AFP 팩트체크 · 영상 재활용",
        "title": "필리핀 지진 영상으로 둔갑한 태국·일본 영상",
        "claim": "2026년 필리핀 지진 직후 고층 건물 피해와 거대한 파도 영상이 현지 피해 장면이라는 설명과 함께 공유됐습니다.",
        "source_name": "AFP Fact Check · Videos from Thailand and Japan falsely linked to Philippine earthquake",
        "source_url": "https://factcheck.afp.com/doc.afp.com.B6KR8G3",
        "media_type": "article",
        "media_url": "",
        "media_caption": "AFP가 영상의 과거 게시 이력과 촬영 지역을 추적한 실제 사례입니다.",
        "source_excerpt": "videos circulating on social media that purportedly show the tremor’s impact were in fact filmed in Thailand and Japan",
        "opening_question": "큰 지진 직후 건물 파손과 파도 영상이 ‘필리핀 현장’이라며 퍼졌어. 실제 재난이 발생했다는 사실만으로 함께 퍼진 영상까지 같은 사건이라고 봐도 될까?",
        "resolution": "AFP는 역이미지 검색과 원 게시물을 통해 건물 영상은 2025년 태국, 파도 영상은 2026년 일본에서 촬영된 것임을 확인했습니다.",
        "clues": ["동일 영상의 더 이른 게시물 검색", "원 게시물의 촬영 장소 설명 확인", "건물 외관·해안 지형을 지도와 비교", "재난 발생 시점과 영상 촬영 시점 분리"],
    },
    {
        "id": "news_turkey_spacex_haarp",
        "label": "Reuters 팩트체크 · 잘못된 설명",
        "title": "튀르키예 지진 전 HAARP 빛으로 퍼진 로켓 영상",
        "claim": "튀르키예 지진 전 하늘의 빛이 HAARP 작동 장면이라는 주장과 함께 영상이 SNS에서 공유됐습니다.",
        "source_name": "Reuters Fact Check · Nighttime footage of bright light in sky unrelated to 2023 Turkey earthquake",
        "source_url": "https://www.reuters.com/fact-check/nighttime-footage-bright-light-sky-unrelated-2023-turkey-earthquake-2024-02-22/",
        "media_type": "article",
        "media_url": "",
        "media_caption": "Reuters가 원 영상을 찾아 촬영 시점과 장소를 확인한 팩트체크입니다.",
        "source_excerpt": "A video of a Space X rocket launch in 2018 in California showing bright light waves in the sky is not related",
        "opening_question": "지진 직전 하늘에 이상한 빛이 보였다는 영상이 ‘HAARP가 지진을 일으킨 증거’라는 설명과 함께 퍼졌어. 영상과 주장 사이의 연결을 확인하려면 무엇부터 봐야 할까?",
        "resolution": "Reuters는 해당 영상이 2018년 미국 캘리포니아에서 촬영된 SpaceX Falcon 9 발사 영상이며 2023년 튀르키예 지진과 관련이 없음을 확인했습니다.",
        "clues": ["영상의 최초 업로드 날짜 확인", "원 영상 설명과 촬영 장소 확인", "과거 뉴스 보도와 동일 장면 비교", "주장과 영상 사이에 실제 인과 근거가 있는지 구분"],
    },
    {
        "id": "news_us_marines_romania",
        "label": "AP 팩트체크 · 영상 오인",
        "title": "이스라엘 도착 미 해병대로 퍼진 루마니아 훈련 영상",
        "claim": "이스라엘-하마스 전쟁 당시 대규모 미 해병대가 이스라엘에 도착했다는 설명과 함께 군인 하차 영상이 공유됐습니다.",
        "source_name": "AP News Fact Focus · Israel-Hamas war misinformation",
        "source_url": "https://apnews.com/article/israel-hamas-gaza-misinformation-fact-check-e58f9ab8696309305c3ea2bfb269258e",
        "media_type": "article",
        "media_url": "",
        "media_caption": "AP가 미 국방부 원 영상을 확인해 부대·장소·촬영 시점을 검증한 사례입니다.",
        "source_excerpt": "The video is from 2022 and shows soldiers from the U.S. Army’s 101st Airborne Division arriving in Romania.",
        "opening_question": "군인들이 비행기에서 내리는 영상에 ‘미 해병대가 이스라엘에 도착했다’는 설명이 붙었어. 군복과 비행기만 보고 장소와 부대를 확정해도 될까?",
        "resolution": "AP는 미 국방부 미디어 원본을 통해 이 영상이 2022년 미 육군 101공수사단이 루마니아에 도착한 장면임을 확인했습니다.",
        "clues": ["원 영상이 어느 기관에서 공개됐는지 확인", "부대명·촬영 장소·촬영 날짜 대조", "같은 영상을 과거 기사에서 검색", "SNS 캡션과 원본 설명을 분리해 확인"],
    },
])

CASE_LIBRARY["deepfake"].extend([
    {
        "id": "deepfake_maryland_principal_audio",
        "label": "AP 보도 · AI 음성 사칭",
        "title": "교장 목소리처럼 만든 인종차별 발언 음성",
        "claim": "미국 메릴랜드의 한 고교에서 교장이 인종차별·반유대 발언을 한 것처럼 들리는 음성이 SNS에 퍼졌습니다.",
        "source_name": "AP News · Athletic director used AI to frame principal with racist remarks",
        "source_url": "https://apnews.com/article/ai-artificial-intelligence-principal-audio-maryland-baltimore-county-pikesville-853ed171369bcbb888eb54f55195cb9c",
        "media_type": "article",
        "media_url": "",
        "media_caption": "AP가 경찰 발표와 기소 문서를 바탕으로 보도한 실제 사건입니다.",
        "source_excerpt": "A high school athletic director in Maryland has been accused of using artificial intelligence to impersonate a principal on an audio recording",
        "opening_question": "학교 관계자의 목소리와 매우 비슷한 녹음이 퍼지고 내용도 충격적이야. 목소리가 비슷하다는 이유만으로 실제 발언이라고 확정해도 될까? 어떤 확인이 필요할까?",
        "resolution": "경찰은 체육부장이 AI를 이용해 교장 목소리를 사칭한 음성을 만들었다고 밝혔고, 분석에서 AI 생성 흔적과 후편집 정황이 확인됐다고 AP가 보도했습니다.",
        "clues": ["녹음의 최초 유포자와 원본 파일 확인", "당사자·학교·수사기관의 공식 확인", "전문 분석 결과와 편집 흔적 확인", "음성 유사성만으로 발언자를 확정하지 않기"],
    },
    {
        "id": "deepfake_hongkong_video_call",
        "label": "Reuters 보도 · 영상회의 사칭",
        "title": "가짜 임원 영상회의로 2,500만 달러 송금",
        "claim": "홍콩에서 직원이 영상회의에 등장한 동료·임원들이 실제라고 믿고 여러 차례 송금해 2,500만 달러가 넘는 피해가 발생한 사례가 알려졌습니다.",
        "source_name": "Reuters · Real insurance coverage for increasing AI deepfake risks",
        "source_url": "https://www.reuters.com/legal/legalindustry/real-insurance-coverage-increasing-ai-deepfake-risks-2024-04-11/",
        "media_type": "article",
        "media_url": "",
        "media_caption": "Reuters가 홍콩 경찰 보도를 인용해 소개한 실제 딥페이크 사기 사례입니다.",
        "source_excerpt": "the Hong Kong deepfake used virtual recreations of numerous employees on a fake video conference",
        "opening_question": "영상회의에 상사와 동료 얼굴이 모두 나오고 송금을 지시했어. 여러 사람이 동시에 화면에 보이면 진짜 회의라고 믿어도 될까? 어떤 독립 확인을 하겠어?",
        "resolution": "Reuters는 홍콩 사건에서 가상으로 재현된 여러 직원이 가짜 영상회의에 등장했고, 피해 직원이 2,500만 달러가 넘는 금액을 송금한 사례를 소개했습니다.",
        "clues": ["영상회의 밖의 기존 연락처로 상사 확인", "큰 송금은 별도 승인 절차 적용", "회의 초대 계정·도메인 확인", "영상 속 다수 인물의 존재 자체를 독립 근거로 보지 않기"],
    },
    {
        "id": "deepfake_ftc_minnesota_son",
        "label": "FTC 공식 회의 사례 · 음성복제",
        "title": "해외 복무 중인 아들 목소리를 복제한 전화",
        "claim": "FTC 공개 회의에서 미네소타의 한 가족이 해외 복무 중인 아들과 똑같이 들리는 다급한 전화를 받은 실제 사례가 소개됐습니다.",
        "source_name": "U.S. Federal Trade Commission · Open Commission Meeting Transcript, Nov. 16, 2023",
        "source_url": "https://www.ftc.gov/system/files/ftc_gov/pdf/transcript-ftc-open-commission-meeting-11.16.23.pdf",
        "media_type": "document",
        "media_url": "",
        "media_caption": "FTC 공개회의 공식 녹취록에 소개된 실제 음성복제 사기 시도입니다.",
        "source_excerpt": "He received a call from someone who sounded just like his son who is currently serving in the military overseas.",
        "opening_question": "해외에 있는 아들과 똑같은 목소리로 다급한 전화가 왔어. 목소리가 일치하면 본인 확인이 끝났다고 볼 수 있을까? 가장 안전한 확인 방법을 말해줘.",
        "resolution": "FTC 녹취록에 따르면 가족은 실제 아들이 아님을 알아차리고 전화를 끊어 금전 피해를 피했습니다. 음성이 익숙해도 별도 연락 경로로 본인을 확인해야 합니다.",
        "clues": ["기존에 저장한 번호로 다시 연락", "다른 가족을 통한 상태 확인", "급박함을 이유로 즉시 송금하지 않기", "목소리 일치와 신원 확인을 구분"],
    },
    {
        "id": "deepfake_ftc_iowa_bail",
        "label": "FTC 공식 회의 사례 · 음성복제",
        "title": "아들 목소리로 7,000달러 보석금을 요구한 전화",
        "claim": "FTC 공개 회의에서 아이오와의 한 부부가 아들처럼 들리는 목소리로 감옥에 있으니 보석금 7,000달러가 필요하다는 전화를 받은 사례가 소개됐습니다.",
        "source_name": "U.S. Federal Trade Commission · Open Commission Meeting Transcript, Nov. 16, 2023",
        "source_url": "https://www.ftc.gov/system/files/ftc_gov/pdf/transcript-ftc-open-commission-meeting-11.16.23.pdf",
        "media_type": "document",
        "media_url": "",
        "media_caption": "FTC 공개회의 공식 녹취록에 소개된 실제 사례입니다.",
        "source_excerpt": "a couple received a panic call from a voice that sounded like their son who was on his way to basic training",
        "opening_question": "아들 목소리로 ‘감옥에 있어서 지금 7,000달러 보석금이 필요하다’는 전화가 왔어. 상황이 급하더라도 송금 전에 무엇을 확인하겠어?",
        "resolution": "FTC 녹취록에 따르면 부부는 실제 아들에게 연락해 안전하게 집에 있다는 사실을 확인하고 송금을 피했습니다.",
        "clues": ["당사자의 기존 연락처로 재확인", "교도소·경찰 등 주장된 기관에 직접 확인", "즉시 송금을 재촉하는 패턴 경계", "다른 가족에게 상황 공유"],
    },
    {
        "id": "deepfake_ftc_utah_grandson",
        "label": "FTC 공식 회의 사례 · 음성복제",
        "title": "손자 목소리로 5,000달러 보석금을 요구한 전화",
        "claim": "FTC 공개 회의에서 유타의 한 남성이 교통사고 뒤 보석금이 필요하다는 손자 목소리의 전화를 받은 실제 사례가 소개됐습니다.",
        "source_name": "U.S. Federal Trade Commission · Open Commission Meeting Transcript, Nov. 16, 2023",
        "source_url": "https://www.ftc.gov/system/files/ftc_gov/pdf/transcript-ftc-open-commission-meeting-11.16.23.pdf",
        "media_type": "document",
        "media_url": "",
        "media_caption": "FTC 공개회의 공식 녹취록의 음성복제 사기 사례입니다.",
        "source_excerpt": "another man got a call from a voice clone that sounded like his grandson claiming to need $5,000 in bail",
        "opening_question": "손자와 똑같이 들리는 목소리가 사고 뒤 보석금 5,000달러가 필요하다고 해. 가족 목소리라는 한 가지 단서만으로 송금해도 될까? 다른 검증 방법을 말해줘.",
        "resolution": "FTC는 이런 음성복제 사례를 소개하며 짧은 음성 샘플만으로도 가족 목소리를 흉내 낼 수 있어 독립된 연락 경로가 필요하다고 설명했습니다.",
        "clues": ["손자의 실제 번호로 다시 연락", "가족만 아는 확인 질문 사용", "보석금 요구 기관을 별도로 확인", "급박한 감정 자극과 신원 확인을 분리"],
    },
    {
        "id": "deepfake_ftc_9400_grandson",
        "label": "FTC 공식 문서 사례 · 음성복제",
        "title": "가짜 손자 보석금 9,400달러를 막은 은행",
        "claim": "FTC 관련 공식 문서에는 사기범이 손자 목소리를 흉내 내 보석금이 필요하다고 속여 노부부가 9,400달러를 잃을 뻔한 사례가 소개됩니다.",
        "source_name": "U.S. Federal Trade Commission · Congressional correspondence on AI-enabled scams",
        "source_url": "https://www.ftc.gov/system/files/ftc_gov/pdf/2023-01209_0.pdf",
        "media_type": "document",
        "media_url": "",
        "media_caption": "FTC 공식 문서에 인용된 실제 음성복제 사기 사례입니다.",
        "source_excerpt": "a scammer used this approach to convince an older couple that the scammer was their grandson in desperate need of money to make bail",
        "opening_question": "손자라고 믿은 목소리가 보석금을 급히 보내 달라고 해서 은행에 갔어. 은행 직원이 의심하기 전까지 진짜라고 믿었다면, 어떤 확인 단계가 빠졌다고 볼 수 있을까?",
        "resolution": "FTC 공식 문서는 은행 직원이 사기 가능성을 알려 부부가 9,400달러를 잃는 것을 피한 사례를 소개합니다. 송금 전 당사자와 독립된 경로로 확인하는 절차가 핵심입니다.",
        "clues": ["가족 당사자에게 별도 번호로 연락", "돈을 받는 계좌·수취인의 관계 확인", "보석금 등 긴급 비용은 기관에 직접 문의", "은행·가족 등 제3자의 확인을 거치기"],
    },
])

CASE_LIBRARY["ai"].extend([
    {
        "id": "ai_zhang_chen",
        "label": "캐나다 법원 사례 · ChatGPT 가짜 판례",
        "title": "Zhang v Chen의 존재하지 않는 판례 2건",
        "claim": "캐나다 가족법 사건에서 변호인이 제출한 신청서에 존재하지 않는 판례 2건이 포함됐고 이후 ChatGPT가 만들어낸 것으로 확인됐습니다.",
        "source_name": "Supreme Court of British Columbia · Zhang v Chen, 2024 BCSC 285 (CanLII 자료)",
        "source_url": "https://www.canlii.org/w/canlii/2024CanLIIDocs3035.pdf",
        "media_type": "document",
        "media_url": "",
        "media_caption": "CanLII가 수록한 Zhang v Chen 판결문 내용에서 확인되는 사례입니다.",
        "source_excerpt": "two non-existent cases, which were discovered subsequently to have been invented by ChatGPT.",
        "opening_question": "AI가 사건명과 판결번호까지 갖춘 판례 두 개를 제시했어. 형식이 법원 판례처럼 완벽해 보여도 업무에 쓰기 전에 무엇을 확인해야 할까?",
        "resolution": "Zhang v Chen에서는 신청서에 포함된 두 사건이 존재하지 않았고 ChatGPT가 만들어낸 것으로 확인됐습니다. 법률 정보는 법원·공식 법률 DB의 원문 존재 여부를 직접 확인해야 합니다.",
        "clues": ["사건명·판결번호를 공식 법률 DB에서 검색", "판결문 원문 직접 열기", "인용된 법리가 실제 쟁점과 일치하는지 확인", "AI 요약만으로 판례 존재를 확정하지 않기"],
    },
    {
        "id": "ai_sanders_usa",
        "label": "미국 연방법원 사례 · AI 가짜 법률근거",
        "title": "Sanders v. USA의 존재하지 않는 AI 판례",
        "claim": "미국 연방청구법원 사건에서 당사자의 서면에 존재하지 않는 AI 생성 법률근거가 인용된 문제가 다뤄졌습니다.",
        "source_name": "U.S. Court of Federal Claims · Sanders v. United States, 2025",
        "source_url": "https://law.justia.com/cases/federal/district-courts/federal-claims/cofce/1:2024cv01301/50466/16/",
        "media_type": "document",
        "media_url": "",
        "media_caption": "미국 연방청구법원 결정문에서 확인되는 실제 사례입니다.",
        "source_excerpt": "Plaintiff’s Filings Cite to Nonexistent, AI-Generated Authority.",
        "opening_question": "AI가 법률 주장과 판례를 한꺼번에 정리해줬어. 내용이 논리적으로 맞아 보인다면 판례 원문 확인을 생략해도 될까? 어떤 순서로 검증하겠어?",
        "resolution": "법원은 원고의 서면이 존재하지 않는 AI 생성 판례를 인용했다고 지적했고, 향후 가짜 AI 법률근거를 다시 제출하면 제재가 가능하다고 경고했습니다.",
        "clues": ["각 판례의 실제 존재 여부 확인", "인용 문구를 판결문 원문과 대조", "AI가 제시한 법리와 실제 판례 결론 비교", "존재하지 않거나 모순되는 판례는 사용하지 않기"],
    },
    {
        "id": "ai_otg_ottogi",
        "label": "미국 연방법원 제재 사례 · AI 환각",
        "title": "OTG New York v. Ottogi America의 AI 가짜 판례",
        "claim": "미국 뉴저지 연방법원 사건에서 변호인이 생성형 AI가 만든 존재하지 않는 판례와 법률 명제를 확인하지 않고 서면에 사용한 사실이 확인됐습니다.",
        "source_name": "U.S. District Court, District of New Jersey · OTG New York v. Ottogi America, 2025",
        "source_url": "https://law.justia.com/cases/federal/district-courts/new-jersey/njdce/2:2024cv07209/550641/48/",
        "media_type": "document",
        "media_url": "",
        "media_caption": "미국 뉴저지 연방법원 제재 결정문입니다.",
        "source_excerpt": "Mr. Cho cited to nonexistent cases and fabricated legal propositions derived from generative artificial intelligence (“AI”)",
        "opening_question": "생성형 AI가 준 판례를 여러 번 프롬프트로 다듬어서 문서에 넣었어. 반복해서 물어봤다는 사실이 검증을 대신할 수 있을까? 무엇을 직접 확인해야 할까?",
        "resolution": "법원은 변호인이 AI가 제공한 환각 판례와 명제를 검증하지 않고 사용했다고 확인하고 Rule 11 위반으로 금전 제재를 부과했습니다.",
        "clues": ["AI 답변 반복이 아닌 외부 원문 검증", "판례명·번호·인용문 각각 확인", "쟁점과 판례 내용의 관련성 확인", "서면 제출 전 사람의 최종 검토"],
    },
    {
        "id": "ai_noland_land_free",
        "label": "캘리포니아 항소법원 사례 · AI 환각",
        "title": "항소서면의 대량 AI 가짜 인용",
        "claim": "캘리포니아 항소 사건에서 서면의 다수 법률 인용과 인용문이 생성형 AI가 만든 허위 내용인 것으로 확인됐습니다.",
        "source_name": "California Court of Appeal · Noland v. Land of the Free, L.P., 2025",
        "source_url": "https://law.justia.com/cases/california/court-of-appeal/2025/b331918.html",
        "media_type": "document",
        "media_url": "",
        "media_caption": "캘리포니아 항소법원이 공개한 실제 판결문입니다.",
        "source_excerpt": "The AI tools created fake legal authority—sometimes referred to as AI “hallucinations”",
        "opening_question": "AI가 서면 전체를 다듬고 다른 AI들로 한 번 더 점검까지 했어. 여러 AI가 비슷하게 답했다면 원 판례를 읽지 않아도 충분히 검증됐다고 볼 수 있을까?",
        "resolution": "법원은 생성형 AI가 만든 허위 법률근거와 인용이 대량으로 포함됐고 변호인이 실제 사건을 읽어 확인하지 않았다고 지적하며 제재를 부과했습니다.",
        "clues": ["여러 AI끼리의 일치가 독립 검증인지 구분", "인용된 모든 판례 원문 읽기", "인용문이 실제 판결문에 있는지 확인", "자동 교정·검수 도구를 최종 검증으로 간주하지 않기"],
    },
    {
        "id": "ai_fletcher_experian",
        "label": "미국 연방항소법원 사례 · AI 미검증",
        "title": "AI로 작성한 항소서면의 인용·사실 오류",
        "claim": "미국 제5연방항소법원은 변호인이 항소 답변서 상당 부분을 AI로 작성한 뒤 생성된 내용의 정확성을 확인하지 않은 사건을 다뤘습니다.",
        "source_name": "U.S. Court of Appeals for the Fifth Circuit · Fletcher v. Experian, 2026",
        "source_url": "https://law.justia.com/cases/federal/appellate-courts/ca5/25-20086/25-20086-2026-02-18.html",
        "media_type": "document",
        "media_url": "",
        "media_caption": "제5연방항소법원의 실제 제재 명령입니다.",
        "source_excerpt": "counsel used artificial intelligence to draft a substantial portion, if not all, of her reply brief and then failed to verify",
        "opening_question": "AI가 글의 구조만 정리했다고 생각했는데 서면 안에 인용·사실 오류가 섞였어. AI를 보조도구로 쓸 때 사용자가 끝까지 확인해야 할 범위는 어디까지라고 생각해?",
        "resolution": "제5연방항소법원은 변호인이 AI를 사용해 서면 상당 부분을 작성했고 생성 내용의 정확성을 검증하지 않았다고 판단해 2,500달러 제재를 명령했습니다.",
        "clues": ["사실 주장과 법률 인용을 각각 원자료와 대조", "AI가 작성한 부분만이 아니라 제출문 전체 검수", "오류 발견 시 즉시 명확하게 정정", "도구 사용 범위를 숨기기보다 정확성 책임을 사람이 부담"],
    },
    {
        "id": "ai_medical_buyers_group",
        "label": "미국 연방법원 제재 사례 · 환각 판례",
        "title": "AI 환각 판례로 1만 달러 변호사비 제재",
        "claim": "미국 연방법원 사건에서 AI가 환각한 존재하지 않는 판례를 인용한 변호인에게 상대방 변호사비 1만 달러를 지급하라는 제재가 내려졌습니다.",
        "source_name": "U.S. District Court, Middle District of Georgia · Medical Buyers Group LLC v. Pence, 2026",
        "source_url": "https://law.justia.com/cases/federal/district-courts/georgia/gamdce/3:2025cv00105/137850/66/",
        "media_type": "document",
        "media_url": "",
        "media_caption": "미국 조지아 중부 연방법원의 실제 제재 결정입니다.",
        "source_excerpt": "ORDERS counsel for Integrity to pay $10,000 in attorney’s fees as sanctions for citing nonexistent cases hallucinated by AI.",
        "opening_question": "AI가 만들어낸 판례를 상대방이 찾지 못해 많은 시간을 들여 확인했다면, ‘실수였으니 고치면 된다’로 끝낼 수 있을까? 제출 전에 어떤 검증 책임이 있다고 생각해?",
        "resolution": "법원은 존재하지 않는 AI 환각 판례를 인용해 상대방이 이를 확인하는 데 시간을 쓰게 한 점을 고려해 1만 달러의 변호사비 제재를 명령했습니다.",
        "clues": ["판례 존재 여부를 제출 전 직접 확인", "상대방이 검증 비용을 떠안지 않도록 사전 검수", "오류 발견 시 신속한 정정", "AI 산출물에 대한 제출자의 최종 책임 인식"],
    },
])

# 안전 검증: 주제별 정확히 9개, ID 중복 없음.
for topic, cases in CASE_LIBRARY.items():
    assert len(cases) == 9, f"{topic}: expected 9 cases, got {len(cases)}"
    ids = [case["id"] for case in cases]
    assert len(ids) == len(set(ids)), f"{topic}: duplicate case id"
